### ISSUE TITLE
Define roles: PHP catchable fatal error

### ISSUE THREAD

**Issue by opp23** [dasistwas/moodle-theme_campus#11]
Define roles: PHP catchable fatal error

Hi, I'm new in Moodle, currently I'm running Moodle 3.3+ (Build: 20170525) with Campus 3.2.1.0 with Campus theme 3.3.0.2 (2017071901) and unfortunately encountered Coding error detected, it must be fixed by a programmer: PHP catchable fatal error in Site administration > UsersPermissions > Define roles

![define roles - php catchable fatal error](https://user-images.githubusercontent.com/6878277/28707423-f2af1d5c-73aa-11e7-82f3-cc33037801b5.JPG)

**Comment by gjb2048** [comment]
Does the issue happen on 3.2.1.0 too?  As will happen on 3.3.0.2 as confused as how you can run two versions of the same theme on the same Moodle installation?

**Comment by opp23** [comment]
Sorry to confuse you with my typo error, the campus theme version I'm using with Moodle 3.3 is Campus 3.3.0.2 (2017071901)

Downloaded file: theme_campus_moodle33_2017071901.zip

Top content of Changes.md

Version Information
26th July 2017 - Version 3.3.0.2
  1. Add custom header and footer settings for HTML forum eMails.


Please see:
[Changes.zip](https://github.com/dasistwas/moodle-theme_campus/files/1186170/Changes.zip)

I also tried to clear caches but the error is still there.

**Comment by opp23** [comment]
Hi, I also encountered another error in Grader Report

![grader report - php catchable fatal error](https://user-images.githubusercontent.com/6878277/28767504-8cd06294-7606-11e7-8f27-653feff92603.JPG)

**Comment by gjb2048** [comment]
Fixed in https://github.com/dasistwas/moodle-theme_campus/commit/a9d726070fa63c5b0e6cff5c3d05d4941b5597f9

**Comment by opp23** [comment]
Hi, thanks for the fix. It's successfully eliminated the errors. However, The **Grader report > View** tab is not properly styled. But the **Setup, Scales, Letters, Import, and Export** tab are properly rendered.

![8-1-2017 4-30-40 pm](https://user-images.githubusercontent.com/6878277/28817681-96454c92-76db-11e7-98b8-8e1b2f38796e.jpg)

**Comment by gjb2048** [comment]
That's a separate issue, please raise one.
