### ISSUE TITLE
Grader report not properly styled on Campus Theme 3.3.0.2 (2017071901)

### ISSUE THREAD

**Issue by opp23** [dasistwas/moodle-theme_campus#12]
This with regards to the [Define roles: PHP catchable fatal error](https://github.com/dasistwas/moodle-theme_campus/issues/11
) which is already fixed and successfully eliminated the errors. However, **The Grader report** > **View** tab is not properly styled. But the Setup, Scales, Letters, Import, and Export tab are properly rendered.

![8-1-2017 4-30-40 pm](https://user-images.githubusercontent.com/6878277/28852766-44adbb7a-775e-11e7-9160-818b512d413e.jpg)

**Comment by gjb2048** [comment]
In what way 'not properly styled' as same as scales:

![ci12_2](https://user-images.githubusercontent.com/1058419/29025553-399bdad6-7b6f-11e7-9e80-7a3ffcaff43c.png)

i.e:

![ci12_1](https://user-images.githubusercontent.com/1058419/29025559-41442a2c-7b6f-11e7-8a5f-a179530f01c4.png)

**Comment by opp23** [comment]
Hi,

On Setup tab, the NAVIGATION and ADMINISTRATION panel is on the left side
![grader report - setup left navigation panel](https://user-images.githubusercontent.com/6878277/29256197-046e6ac4-80db-11e7-8b52-e121011d43fe.jpg)


While on the View tab, the NAVIGATION and ADMINISTRATION panel is at the bottom
![grader report - view bottom navigation panel](https://user-images.githubusercontent.com/6878277/29256202-12bee946-80db-11e7-902e-fdfa3cbf2b57.jpg)

**Comment by gjb2048** [comment]
This is not a bug but intentional in order to provide more space for the grader report.  Therefore 'not properly' is an opinion of style rather than a fact of correctness.

**Comment by opp23** [comment]
I stand corrected. Thanks..
