### ISSUE TITLE
Updates to theme are not shown in Moodle and do not install via Moodle.org

### ISSUE THREAD

**Issue by hermannkm** [dasistwas/moodle-theme_campus#13]
I do not get any message from Moodle when searching for updates even when there is a new version of campus available (today: 3.3.0.3 instead of 3.3.0.2).
But updating via downloaded zip is working. Using Moodle 3.3 weekly updated.

**Comment by gjb2048** [comment]
Everything on Moodle.org is correct for V3.3.0.3 entry, therefore issue with Moodle.org, please raise via their tracker.

**Comment by hermannkm** [comment]
You have been right, did this, wasn't a issue there either. The simple cause was MATURITY_BETA in campus updates and my settings for Site administration > Server > Update notifications > Required code maturity (was: "Stable"). Sorry.
