### ISSUE TITLE
Syntax error when clicking responsive menu

### ISSUE THREAD

**Issue by japochino** [dasistwas/moodle-theme_campus#14]
Hello 

In mobile view, when I click the icon in order to expand the menu, I get the following error:

Error: Syntax error, unrecognized expression: #
jquery-3.1.0.min.js:1:13126

Any help?

**Comment by japochino** [comment]
The same issue occurs when clicking a menu item wich has a submenu. And the submenu does not display.

**Comment by japochino** [comment]
As described here: https://bitbucket.org/covuni/moodle-theme_adaptable/issues/617/jquery-throws-syntax-error-on-click
The reason seems to be jquery, who doesn't like # char in href atributtes. 
Do you have a fix for this? It's urgent for me because of of a angry client. If I don't fix this quicly I'll have to discard the theme! And I don't want this.

Thanks!

**Comment by gjb2048** [comment]
Seen this years ago and sure it was rectified.  What version of Moodle and the theme are you using?

**Comment by japochino** [comment]
Moodle 3.3.2 (Build: 20170911) and Campus 3.3.0.3

Thanks!

**Comment by gjb2048** [comment]
Please post a screen short of the issue so I know where to look.

**Comment by japochino** [comment]
![screenshot--2018-01-25-16-56-34](https://user-images.githubusercontent.com/7734350/35397942-1133dbc6-01f1-11e8-8bd0-3ea053564caa.png)

**Comment by gjb2048** [comment]
Thanks, ok that is not a standard menu like the language menu, is the the custom menu?  How was it created, please detail and post the menu text structure if it was the custom menu.

**Comment by gjb2048** [comment]
Have you made any changes to the code as supplied?  If so, what?  Also are there any other third party plugins installed?  If so, which?

**Comment by japochino** [comment]
No, I didn't. The problem seems to be in the href atributte of the menu items (which starts by '#')

**Comment by gjb2048** [comment]
I understand that, but "ok that is not a standard menu like the language menu, is the the custom menu? How was it created, please detail and post the menu text structure if it was the custom menu.".

**Comment by japochino** [comment]
For that menu I used the custommenuitems param in theme settings. The whole value is: 

Inicio|http://trainingsvenson.com||es
Recepción|||es
- Tablón de anuncios |http://trainingsvenson.com/mod/page/view.php?id=9||es
Centro e-learning|||es
- Catálogo e-learning |#||es
-- Incorporación |http://trainingsvenson.com/course/index.php?categoryid=10||es
-- Productividad |http://trainingsvenson.com/course/index.php?categoryid=11||es
-- Comercial |http://trainingsvenson.com/course/index.php?categoryid=12||es
-- Técnico |http://trainingsvenson.com/course/index.php?categoryid=13||es
-- Habilidades |http://trainingsvenson.com/course/index.php?categoryid=14||es
- Píldoras Formativas|http://trainingsvenson.com/mod/page/view.php?id=257||es
Biblioteca|http://trainingsvenson.com/mod/page/view.php?id=261||es

Home|http://trainingsvenson.com||en
Reception|||en
- Bulletin board|#||en
E-learning center|||en
- E-learning catalogue|#||en
- Formative pills|#||en
Library|#||en

Zuhause|http://trainingsvenson.com||de
Empfang|||de
- Schwarzes brett|#||de
E-Learning Center|||de
- E-Learning Katalog |#||de
- Formative Pills|#||de
Bibilothek|#||de

Casa|http://trainingsvenson.com||pt
Recepção|||pt
- Quadro de avisos|#||pt
E-learning center|||pt
- Catálogo de e-learning|#||pt
- Pills formativos|#||pt
Biblioteca|#||pt

#####

**Comment by gjb2048** [comment]
Nothing wrong with the theme!  It is your data, so changing:

Catálogo e-learning |#||es

to:

Catálogo e-learning |||es

solves the problem!

**Comment by japochino** [comment]
Great! Thank you so much!
