### ISSUE TITLE
Mail from Announcements Forum do not display header picture from frontpagebackground

### ISSUE THREAD

**Issue by hermannkm** [dasistwas/moodle-theme_campus#16]
I am using a background picture in campus theme. This seems to be included in mails from the standard announcement forums. 
<img width="769" alt="bildschirmfoto 2018-05-28 um 16 58 57" src="https://user-images.githubusercontent.com/12869273/40620338-bd7906ec-6298-11e8-8fad-a19541132cb3.png">

As I run my site on https:// the link inserted into the mail, which is
`http://moodle.klocker-mark.eu/pluginfile.php/1/theme_campus/frontpagebackgrou=
ndimage/1501210797/norcia2.png`
does/can not work. Perhaps this is moodle related and not campus.

**Comment by dasistwas** [comment]
The image has to be available publicly without any login. So you can use for example links to images on your moodle site, that can be accessed without login or you link images on wikimedia.org, etc.. You can not use images from courses, etc., that require login.

**Comment by hermannkm** [comment]
OK, sorry, but where is the configuration for these images? This link is an exact copy of the link campus theme generates for my site without login. Is the layout for the emails produced by the theme -- or did I change this manually (really sorry, if I forgot)?

**Comment by gjb2048** [comment]
Odd, as the code is:

$hdbackgroundimage = $PAGE->theme->setting_file_url('frontpagebackgroundimage', 'frontpagebackgroundimage');

which uses the core setting_file_url method which should be returning https.

If you've changed to https recently, then do a 'Purge all caches'.

**Comment by dasistwas** [comment]
maybe switching to https did not work out 100%. I recommend to use https conversion tool:
https://moodle.klocker-mark.eu/admin/tool/httpsreplace/index.php

**Comment by dasistwas** [comment]
And update your image there:
https://moodle.klocker-mark.eu/admin/settings.php?section=theme_campus_forum

**Comment by hermannkm** [comment]
Thank you, the last one worked instantly!
