### ISSUE TITLE
Customized category header not showing for grading view

### ISSUE THREAD

**Issue by hermannkm** [dasistwas/moodle-theme_campus#2]
I customized the headers for some courses which works beautifully. When switching to grading the original header is showing.

So in my course e.g. in _http://moodle.klocker-mark.at/course/view.php?id=29_ the correct custom header is shown, switching to grading in the same course, that is _http://moodle.klocker-mark.at/grade/report/user/index.php?id=29_, the original header is shown.

No problem at all for working (the table now is perfect, thank you!), just surprising.

**Comment by gjb2048** [comment]
Ok....
1. Cannot see anything as no guest access on URL's specified.  But... can deduce what is happening.
2. Unexpected, but probably should be the course and not other header.
3. Fixing is tricky and need to think as report layout used outside of courses but course ID is that of site, so need to use that.

**Comment by gjb2048** [comment]
Note to self 'format-site' instead.

**Comment by dasistwas** [comment]
Hi,

thank you for reporting that. Could you give us the moodle version and the theme version you are using? How do your headers differ? Did you change the header images? What changes did you do exactly? That information would be very helpful for us.

Thank you.
David

**Comment by hermannkm** [comment]
Hi David,
1. Reacting to yesterdays message from Gareth I added a user in a special course to view the problem (it is not visible as a guest as you can see no grades then). So you can see yourself what is happening here:
   This is the course page: http://moodle.klocker-mark.at/course/view.php?id=3&lang=en http://moodle.klocker-mark.at/course/view.php?id=3&lang=en
   This happens when switching to grades: http://moodle.klocker-mark.at/grade/report/user/index.php?id=3 http://moodle.klocker-mark.at/grade/report/user/index.php?id=3
   I think you have to login as campus/Campus15!
2. My moodle version and the theme should be the latest as of today, that is Moodle http://moodle.org/ 2.9.1 (Build: 20150706) http://docs.moodle.org/dev/Releases, campus 2.9.1.
3. I did two things in campus config leaving all other options as default.
   a) check my category in Header/coursecategoryhavecustomheader1
   b) upload a logo and a Background image in theme_campus | coursecategorylogo1 and coursecategorybackgroundimage1

Hope this helps,

Hermann

**Comment by gjb2048** [comment]
Fixed in https://github.com/dasistwas/moodle-theme_campus/commit/7749975f22d19366a1c982f348942590326b9dc7
