### ISSUE TITLE
Validator: ul within ul not permitted

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-theme_campus#20]
There is a ul within ul, which throws an error on html validation:

https://github.com/Wunderbyte-GmbH/moodle-theme_campus/blob/dd3f42796fcf53866fe5f9e826e49217d75ba7ed/layout/tiles/navbar.php#L43

**Comment by gjb2048** [comment]
@dasistwas Odd as you can have nested lists: https://www.w3schools.com/tags/tag_ul.asp - but perhaps because of ul > ul and not ul > li > ul

**Comment by dasistwas** [comment]
Like this
```
 <ul>
  <li>Coffee</li>
  <li>Tea
    <ul>
      <li>Black tea</li>
      <li>Green tea</li>
    </ul>
  </li>
  <li>Milk</li>
</ul> 
```

**Comment by gjb2048** [comment]
Yes

**Comment by gjb2048** [comment]
@dasistwas Looked at it, tried something out, seems fine, actually nesting not needed!  Elements already 'pulled right' - master_dev for M3.9 updated.

**Comment by dasistwas** [comment]
thank you for fixing this.
