### ISSUE TITLE
Problem after login

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-theme_campus#21]
After I login on www.nachqualifizierung.at I get this error:
```

 Fehler: Class 'theme_campus\output\stdClass' not found
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 881 of /theme/campus/classes/output/core_renderer.php: Error thrown
    line 50 of /theme/campus/layout/tiles/footer.php: call to theme_campus\output\core_renderer->login_info()
    line 76 of /theme/campus/layout/frontpage1.php: call to require_once()
    line 1374 of /lib/outputrenderers.php: call to include()
    line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 100 of /index.php: call to core_renderer->header()
```

**Comment by dasistwas** [comment]
We have a special branch for adding some custom headers. https://github.com/Wunderbyte-GmbH/moodle-theme_campus/commit/8cc7fcc046efcdc34729069820cba06dfdfcfe69

Maybe it only concerns that branch.

@gjb2048 could you have a  look at that?

**Comment by gjb2048** [comment]
@dasistwas I saw the issue on the 'master_dev' branch too.  I'm not sure how to replicate, however the fix https://github.com/Wunderbyte-GmbH/moodle-theme_campus/commit/4fb052275b0407e246b7eeb12d807ca9e1c0bad3 should do the trick.  Fix is on the 'master_branch' and not tested!

**Comment by dasistwas** [comment]
Thank you, the fix is working!
