### ISSUE TITLE
Custom font for campus

### ISSUE THREAD

**Issue by mahmoodn** [dasistwas/moodle-theme_campus#6]
How can I add a custom font in campus theme? I read some documents about modifying css file, but I can not find the keywords in the documents in campus/style/custom.css

**Comment by gjb2048** [comment]
Duplicate question of: https://moodle.org/mod/forum/discuss.php?d=349072

Please read: https://docs.moodle.org/32/en/How_to_add_custom_fonts_in_a_theme

**Comment by mahmoodn** [comment]
yes that is me on the moodle forum!
I created a font-face{} but I don't see a  page-hear section. The font I want to add is a non-english font for RTL languages. Please let me know where to add that because I like the them

Since the question is directly related to this theme, I decided to ask here

**Comment by gjb2048** [comment]
Hi,

The theme comes with no support.  Please continue to use the themes forum.

Gareth
