### ISSUE TITLE
Course name appears in navbar when set to appear only in page content

### ISSUE THREAD

**Issue by yanakonst** [dasistwas/moodle-theme_campus#8]
Hi,

I'm running moodle 3.1+ (but seen this bug in 3.2 too :) )
So i set the "Course and category page 'page heading' location" to be at the Top of page content".

![image](https://cloud.githubusercontent.com/assets/6485955/25344519/0caefb62-291b-11e7-84d9-0ae5f150c285.png)

On the main course page everything is ok, and the name apperas correctly:

![image](https://cloud.githubusercontent.com/assets/6485955/25344664/758ebbae-291b-11e7-9237-639ed446197a.png)

But as soon as i go to a different page in the course, lets say the grades page, the course title is displayed in the nav bar. moving all text that appears there and showing only part of the name course.

![image](https://cloud.githubusercontent.com/assets/6485955/25344742/b629e756-291b-11e7-818b-1a9b88bc414d.png)

In case it's not clear i don't want the course name to appear on the nav bar at any point.

Thanks

Yana

**Comment by gjb2048** [comment]
A look at the grader report screen shot shows that the block region is along side, thus different to the supplied code, what customisations do you have?

**Comment by gjb2048** [comment]
For a setting value of 4 'get_header_file()' implies four layouts (course, coursecategory, incourse and report) when in effect with values of 1 and 3 there is just 'course' and 'coursecategory'.

**Comment by gjb2048** [comment]
Fixed in M3.1 and M3.2 versions.

**Comment by yanakonst** [comment]
Thanks for the quick fix!!!
